extensions:
  MagicHash: true
  OverloadedStrings: true
cabal-file: project.cabal
version: 1
module-template: ! 'module MODULE_NAME where

'
modules:
  Main(src/Main.hs):
    filename: src/Main.hs
  MyMod:
    filename: src/MyMod.hs
